name: docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [normal, full]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set build target (normal)
        if: matrix.flavor == 'normal'
        run: |
          echo "build_file=Dockerfile" >> $GITHUB_ENV
          echo "image_tag=" >> $GITHUB_ENV

      - name: Set build target (full)
        if: matrix.flavor == 'full'
        run: |
          echo "build_file=Dockerfile.full" >> $GITHUB_ENV
          echo "image_tag=:full" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./${{ env.build_file }}
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/latexmk${{ env.image_tag }}
          platforms: linux/amd64
          push: true